// src/components/Navbar.svelte
<script>
    import { faSun, faMoon } from "@fortawesome/free-solid-svg-icons";
    import { FontAwesomeIcon } from "fontawesome-svelte";

    const config = window.yukitoki.config;
    let currentTheme = window.yukitoki.theme;

    function toggleMobileMenu(ev) {
        ev.preventDefault();
        const elm = document.getElementById("mobile-menu");
        if (!elm) return;
        elm.classList.toggle("hidden");
    }

    function toggleTheme() {
        window.yukitoki.toggleTheme();
        currentTheme = window.yukitoki.theme;
    }
</script>

<header class="bg-blurple-600 sticky top-0 z-20" id="container">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="relative flex items-center justify-between h-16">
            <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
                <div class="flex-shrink-0 flex items-center">
                    <a href={config.NAV.ICON.HREF ?? "/"} class="block h-8 w-auto">
                        {#if config.NAV.ICON.TYPE === "IMAGE"}
                            <img src={config.NAV.ICON.VALUE} alt="img" />
                        {:else}
                            <h1 class="text-white text-lg font-semibold select-none">{config.NAV.ICON.VALUE}</h1>
                        {/if}
                    </a>
                </div>
                <div class="hidden sm:block sm:ml-6">
                    <div class="flex space-x-4 ml-auto mr-auto">
                        {#each config.NAV.BUTTONS as nav}
                            {#if nav.newPage}
                                <a href={nav.path} rel="noreferrer" target="_blank" class="text-white hover:opacity-70 px-3 py-2 rounded-md text-sm font-medium" aria-current="page">{nav.label} </a>
                            {:else}
                                <a href={nav.path} class="text-white hover:opacity-70 px-3 py-2 rounded-md text-sm font-medium" aria-current="page">{nav.label} </a>
                            {/if}
                        {/each}
                    </div>
                </div>
            </div>

            <div class="absolute inset-y-0 right-0 items-center hidden md:block pt-3">
                <button on:click={toggleTheme} type="button" class="inline-flex items-center justify-center p-2 rounded-md text-white text-2xl" aria-controls="mobile-menu" aria-expanded="false">
                    <span class="sr-only">#</span>
                    <FontAwesomeIcon icon={currentTheme === "dark" ? faSun : faMoon} />
                </button>
            </div>

            <div class="absolute inset-y-0 right-0 flex items-center sm:hidden">
                <button on:click={toggleMobileMenu} type="button" class="inline-flex items-center justify-center p-2 rounded-md text-white" aria-controls="mobile-menu" aria-expanded="false">
                    <span class="sr-only">#</span>
                    <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                    <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <div class="sm:hidden hidden" id="mobile-menu">
        <div class="px-2 pt-2 pb-3 space-y-1">
            {#each config.NAV.BUTTONS as nav}
                {#if nav.newPage}
                    <a href={nav.path} rel="noreferrer" target="_blank" class="text-white block hover:opacity-70 px-3 py-2 rounded-md text-base font-medium" aria-current="page">
                        {nav.label}
                    </a>
                {:else}
                    <a href={nav.path} class="text-white block hover:opacity-70 px-3 py-2 rounded-md text-base font-medium" aria-current="page">
                        {nav.label}
                    </a>
                {/if}
            {/each}
            <button on:click={toggleTheme} type="button" class="p-2 rounded-md text-white text-2xl" aria-controls="mobile-menu" aria-expanded="false">
                <span class="sr-only">#</span>
                <FontAwesomeIcon icon={currentTheme === "dark" ? faSun : faMoon} />
            </button>
        </div>
    </div>
</header>

// components/Navbar.jsx
import Link from "next/link";
import { SITE_NAME, NAV_LINKS } from "../config";

export default function Navbar() {

    return (
        <section>
            <nav className="relative py-6 bg-gray-800">
                <div className="container mx-auto px-4 flex justify-between items-center">
                    <Link href="/">
                        <a className="text-3xl font-bold leading-none text-gray-200">{SITE_NAME}</a>
                    </Link>
                    <div className="lg:hidden">
                        <button className="navbar-burger flex items-center text-gray-600 p-3" onClick={() => document.getElementById('mobile_menu').classList.remove('hidden')}>
                            <svg className="block h-4 w-4 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
                            </svg>
                        </button>
                    </div>
                    <ul className="hidden absolute top-1/2 left-3/4 transform -translate-y-1/2 -translate-x-1/2 lg:mx-auto lg:flex lg:items-center lg:w-auto lg:space-x-6">
                        {
                            NAV_LINKS.map((m, i) => {
                                if (m.external) return (
                                    <li key={i}>
                                        <a className="text-sm text-gray-400 hover:text-gray-500" href={m.path} target="_blank">{m.name}</a>
                                    </li>
                                )

                                return (
                                    <li key={i}>
                                        <Link href={m.path}>
                                            <a className="text-sm text-gray-400 hover:text-gray-500">{m.name}</a>
                                        </Link>
                                    </li>
                                )
                            })
                        }
                    </ul>
                </div>
            </nav>
            <div className="hidden navbar-menu relative z-50" id="mobile_menu">
                <div className="navbar-backdrop fixed inset-0 bg-gray-800 opacity-25"></div>
                <nav className="fixed top-0 left-0 bottom-0 flex flex-col w-5/6 max-w-sm py-6 px-6 overflow-y-auto bg-gray-800">
                    <div className="flex items-center mb-8">
                        <Link href="/">
                            <a className="mr-auto text-3xl font-bold leading-none text-gray-200">{SITE_NAME}</a>
                        </Link>
                        <button className="navbar-close" onClick={() => document.getElementById('mobile_menu').classList.add('hidden')}>
                            <svg className="h-6 w-6 text-gray-400 cursor-pointer hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path>
                            </svg>
                        </button>
                    </div>
                    <div>
                        <ul>
                            {
                                NAV_LINKS.map((m, i) => {
                                    if (m.external) return (
                                        <li className="mb-1" key={i}>
                                            <a className="block p-4 text-sm font-semibold text-gray-400 hover:bg-gray-600 rounded" href={m.path} target="_blank">{m.name}</a>
                                        </li>
                                    )

                                    return (
                                        <li className="mb-1" key={i}>
                                            <Link href={m.path}>
                                                <a onClick={() => document.getElementById('mobile_menu').classList.add('hidden')} className="block p-4 text-sm font-semibold text-gray-400 hover:bg-gray-600 rounded">{m.name}</a>
                                            </Link>
                                        </li>
                                    )
                                })
                            }
                        </ul>
                    </div>
                </nav>
            </div>
        </section>
    )
}
