// components/docs/Sidebar.jsx
import { useState, useEffect } from "react";
import { Converter } from "showdown";
import Viewer from "./Viewer";
import hljs from "highlight.js";
import "highlight.js/styles/monokai-sublime.css";
import { useRouter } from "next/router";
import ErrorPage from "./Error";
import Link from "next/link";

const params = ["classes", "typedefs"];
const mdconv = new Converter({
    tables: true,
    ghCodeBlocks: true,
    emoji: true,
    ghCompatibleHeaderId: true
});

const makeHTML = (md) => mdconv.makeHtml(md);

export default function Sidebar({ docs }) {
    const router = useRouter();
    const path = router.query.path || "";
    if (!docs) return <ErrorPage />;

    const [docsContent, setDocsContent] = useState({ jsx: false, data: null, path: null });
    const data = Object.keys(docs)
        .filter((a) => params.includes(a))
        .map((m) => ({ name: m, data: docs[m] }));

    const custom = Object.values(docs.custom);

    if (!path) {
        const def = Object.values(custom[0].files)[0];
        window.location.href += `?path=${def.path.split("/").slice(1).join("/").split(".").shift()}`;
    } else {
        if (path !== docsContent.path) {
            const [name, fileName] = path.split("/");
            const nc = ["classes", "typedefs"];
            if (nc.includes(name)) {
                const file = docs[name].find((f) => f.name === fileName);
                if (!file) return <ErrorPage path={`/docs?path=${path}`} />;
                file.head = name;
                navigate(file.name, null, file);
            } else {
                if (
                    !custom.find((x) => x.files[fileName] !== undefined) ||
                    !custom.find((x) => x.files[fileName] !== undefined).files[fileName]
                )
                    return <ErrorPage path={`/docs?path=${path}`} />;

                navigate(fileName, null);
            }
        }
    }

    useEffect(() => {
        document.body.classList.add("bg-gray-800");
        highlight();
    });

    const handler = (e) => e.preventDefault();

    function navigate(navigateTo, e, notCustom = false) {
        if (e) handler(e);

        if (!notCustom) {
            const loc = custom.find((x) => x.files[navigateTo] !== undefined);
            const file = loc.files[navigateTo];

            if (file.type === "js") file.content = `\`\`\`js\n${file.content}\`\`\``;

            setDocsContent({
                jsx: false,
                data: makeHTML(file.content),
                raw: file,
                path: file.path.split("/").slice(1).join("/").split(".").shift()
            });
        } else {
            setDocsContent({ jsx: true, data: notCustom, raw: notCustom, path: `${notCustom.head}/${notCustom.name}` });
        }
    }

    function highlight() {
        document.querySelectorAll("pre code").forEach((el) => {
            hljs.highlightBlock(el);
        });
    }

    return (
        <div className="relative container mx-auto bg-gray-900">
            <div className="space-x-4 py-5 inline-flex bg-gray-900">
                <div className="lg:hidden">
                    <button
                        className="navbar-burger flex items-center text-gray-600 p-3"
                        onClick={() => document.getElementById("doc_mobile").classList.toggle("hidden")}
                    >
                        <svg
                            className="h-6 w-6 text-gray-400 cursor-pointer hover:text-gray-500"
                            xmlns="http://www.w3.org/2000/svg"
                            fill="currentColor"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                        >
                            <path d="M24 22h-24l12-20z" />
                        </svg>
                    </button>
                </div>
                <div className="hidden sm:block" id="doc_mobile">
                    <div className="min-h-screen flex flex-col flex-auto flex-shrink-0 antialiased bg-gray-900 text-gray-50">
                        <div className="flex flex-col top-0 left-0 w-64 bg-gray-900 h-full">
                            <div className="overflow-y-auto overflow-x-auto flex-grow">
                                <ul className="flex flex-col py-6 space-y-1">
                                    {
                                        /* Custom Doc File */
                                        custom.map((m, i) => {
                                            const params = Object.values(m.files);
                                            const keys = Object.keys(m.files);

                                            return (
                                                <>
                                                    <li className="px-5" key={i}>
                                                        <div className="flex flex-row items-center h-8">
                                                            <div className="flex font-semibold text-sm text-gray-300 my-4 font-sans uppercase">
                                                                {m.name}
                                                            </div>
                                                        </div>
                                                    </li>
                                                    {params.map((n, j) => {
                                                        return (
                                                            <li key={i + j}>
                                                                <Link
                                                                    href={`/docs?path=${n.path
                                                                        .split("/")
                                                                        .slice(1)
                                                                        .join("/")
                                                                        .split(".")
                                                                        .shift()}`}
                                                                >
                                                                    <a
                                                                        href="#"
                                                                        className="relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-700 text-gray-500 hover:text-gray-200 border-l-4 border-transparent hover:border-blue-500 pr-6"
                                                                    >
                                                                        <span className="inline-flex justify-center items-center ml-4">
                                                                            <svg
                                                                                className="w-5 h-5"
                                                                                fill="none"
                                                                                stroke="currentColor"
                                                                                viewBox="0 0 24 24"
                                                                                xmlns="http://www.w3.org/2000/svg"
                                                                            >
                                                                                <path
                                                                                    strokeLinecap="round"
                                                                                    strokeLinejoin="round"
                                                                                    strokeWidth="2"
                                                                                    d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"
                                                                                ></path>
                                                                            </svg>
                                                                        </span>
                                                                        <span className="ml-2 font-semibold text-sm tracking-wide truncate font-sans">
                                                                            {n.name}
                                                                        </span>
                                                                    </a>
                                                                </Link>
                                                            </li>
                                                        );
                                                    })}
                                                </>
                                            );
                                        })
                                    }

                                    {
                                        /* Classes, Typedefs etc */
                                        data.map((m, i) => {
                                            const params = Object.keys(m.data);

                                            return (
                                                <>
                                                    <li className="px-5" key={i}>
                                                        <div className="flex flex-row items-center h-8">
                                                            <div className="flex font-semibold text-sm text-gray-300 my-4 font-sans uppercase">
                                                                {m.name}
                                                            </div>
                                                        </div>
                                                    </li>
                                                    {params.map((n, j) => {
                                                        return (
                                                            <li key={i + j}>
                                                                <Link href={`/docs?path=${m.name}/${m.data[n].name}`}>
                                                                    <a
                                                                        href="#"
                                                                        className="relative flex flex-row items-center h-11 focus:outline-none hover:bg-gray-700 text-gray-500 hover:text-gray-200 border-l-4 border-transparent hover:border-blue-500 pr-6"
                                                                    >
                                                                        <span className="inline-flex justify-center items-center ml-4">
                                                                            <svg
                                                                                className="w-5 h-5"
                                                                                fill="none"
                                                                                stroke="currentColor"
                                                                                viewBox="0 0 24 24"
                                                                                xmlns="http://www.w3.org/2000/svg"
                                                                            >
                                                                                <path
                                                                                    strokeLinecap="round"
                                                                                    strokeLinejoin="round"
                                                                                    strokeWidth="2"
                                                                                    d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"
                                                                                ></path>
                                                                            </svg>
                                                                        </span>
                                                                        <span className="ml-2 font-semibold text-sm tracking-wide truncate font-sans">
                                                                            {m.data[n].name}
                                                                        </span>
                                                                    </a>
                                                                </Link>
                                                            </li>
                                                        );
                                                    })}
                                                </>
                                            );
                                        })
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="docs-container px-5 lg:border-l-2 lg:border-gray-300 min-w-min">
                    <div id="docs-content" className="text-white prose">
                        <Viewer data={docsContent} />
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/components/Sidebar.svelte
<script>
    import { params, url } from "@roxi/routify";
    import { FontAwesomeIcon } from "fontawesome-svelte";
    import { faChevronCircleRight, faTimesCircle } from "@fortawesome/free-solid-svg-icons";

    export let data;

    let currentBranch = data[0].tag,
        currentID = data[0].id;

    const { source, tag, category, file } = $params;
    let currentDoc = data.find((x) => x.tag === tag && x.id === source);

    function updateData() {
        const src = document.getElementById("docsource");
        const branch = document.getElementById("docbranch");

        window.location.href = `/docs/${src?.value ?? source}/${branch?.value ?? tag}${category ? `/${category}` : ""}${file ? `/${file}` : ""}`;
    }

    const sidebarProps = ["custom", "classes", "typedefs"]
        .map((m) => {
            const d = currentDoc[m];
            return { type: m, data: d };
        })
        .filter((x) => !!x);

    function toggleSidebar() {
        const elm = document.getElementById("sidebar-panel");
        if (elm) {
            elm.classList.toggle("-translate-x-full");
        }
    }
</script>

<div class="absolute left-0 flex items-center md:hidden">
    <button on:click={toggleSidebar} type="button" class="inline-flex items-center justify-center p-2 rounded-md text-white" aria-controls="mobile-menu" aria-expanded="false">
        <span class="sr-only">#</span>
        <button class="bg-blurple-600 text-2xl p-2">
            <FontAwesomeIcon icon={faChevronCircleRight} />
        </button>
    </button>
</div>

<div class="inline-block fixed lg:block lg:relative bg-white dark:bg-gray-800 transition sidebar transform-gpu -translate-x-full lg:translate-x-0 mb-5" id="sidebar-panel">
    <div class="sticky top-0 overflow-y-auto overflow-x-hidden w-72 md:w-80 sidebar-height">
        <div class="absolute right-0 flex items-center md:hidden">
            <button on:click={toggleSidebar} type="button" class="inline-flex items-center justify-center p-2 rounded-md text-white" aria-controls="mobile-menu" aria-expanded="false">
                <span class="sr-only">#</span>
                <button class="bg-blurple-600 text-2xl p-2">
                    <FontAwesomeIcon icon={faTimesCircle} />
                </button>
            </button>
        </div>

        <nav class="my-5 px-2 space-y-1 z-10 py-3 select-none">
            <ul>
                <li class="flex flex-col">
                    <label for="docsource" class="font-semibold text-lg">Source</label>
                    <select on:input={updateData} id="docsource" class="form-select rounded-md border-transparent bg-gray-100 focus:border-gray-500 focus:bg-white focus:ring-0 text-black">
                        {#each [...new Set(data.map((m) => m.id))] as doc}
                            <option value={doc} selected={doc === source ? "true" : "false"}>{doc}</option>
                        {/each}
                    </select>
                </li>
                <li class="flex flex-col">
                    <label for="docbranch" class="font-semibold text-lg">Branch</label>
                    <select on:input={updateData} id="docbranch" class="form-select rounded-md border-transparent bg-gray-100 focus:border-gray-500 focus:bg-white focus:ring-0 text-black">
                        {#each data.filter((x) => x.id === currentID) as doc}
                            <option value={doc.tag} selected={tag === doc.tag ? true : false}>{doc.tag}</option>
                        {/each}
                    </select>
                </li>
            </ul>
            {#each sidebarProps as prop}
                {#if prop.type === "custom"}
                    {#each Object.keys(prop.data) as item}
                        <label for="files" class="font-semibold text-lg uppercase">{prop.data[item].name}</label>
                        <ul id="files">
                            {#each Object.entries(prop.data[item].files) as [filename, file]}
                                <li class="sidebar-item-selector">
                                    <a target="_self" href={$url(`/docs/${source}/${tag}/${item}/${filename}`)}>{file.name}</a>
                                </li>
                            {/each}
                        </ul>
                    {/each}
                {:else}
                    <label for={prop.type} class="font-semibold text-lg uppercase">{prop.type}</label>
                    <ul id={prop.type}>
                        {#each Object.values(prop.data) as item}
                            <li class="sidebar-item-selector">
                                <a target="_self" href={$url(`/docs/${source}/${tag}/${prop.type}/${item.name}`)}>{item.name}</a>
                            </li>
                        {/each}
                    </ul>
                {/if}
            {/each}
        </nav>
    </div>
</div>

<style>
    .sidebar-height {
        height: calc(100vh - theme("height.16"));
    }

    .sidebar::before {
        content: "";
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        width: 999em;
        pointer-events: none;
    }

    .sidebar-item-selector {
        padding-left: 1rem;
    }

    .sidebar-item-selector:hover {
        background-color: #7289da;
        cursor: pointer;
        color: #ffffff;
    }
</style>
